doFencedCodeBlocks must be public
doFencedCodeBlocks extends from MarkdownParser -> MarkdownExtraParser, where it has no visibility defined, so it's public.

Fatal error: Access level to ServerGrove\KbBundle\Util\MarkdownParser::doFencedCodeBlocks() must be public (as in class dflydev\markdown\MarkdownExtraParser) in /Users/raulfraile/Sites/servergrove/kb/vendor/servergrove/kb-bundle/ServerGrove/KbBundle/Util/MarkdownParser.php on line 13